import type { GetServerSideProps, GetStaticProps, InferGetServerSidePropsType, InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export const  getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch('http://localhost:3000/api/post')
  return {
    props: {data: await res.json()}
  }
}

const Home: NextPage = ({data}: InferGetStaticPropsType<typeof getStaticProps>) => {
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          92thunder.dev
        </h1>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
