DROP DATABASE IF EXISTS blog;
CREATE DATABASE blog;
DROP TABLE IF EXISTS blog.post;
CREATE TABLE blog.post (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  title VARCHAR(64) NOT NULL,
  body TEXT NOT NULL,
  published BOOLEAN NOT NULL,
  published_at VARCHAR(32) NOT NULL
);

DROP TABLE IF EXISTS blog.account;
CREATE TABLE blog.account (
  secret VARCHAR(64) NOT NULL PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  url VARCHAR(256) NOT NULL,
  failed_count int(11) DEFAULT NULL,
  locked_at DATETIME DEFAULT NULL
);

DROP TABLE IF EXISTS blog.session;
CREATE TABLE blog.session (
  id VARCHAR(64) NOT NULL PRIMARY KEY
);